// https://www.englishpage.com/gerunds/index.htm
const consts = require('./consts');

module.exports = [
  {
    title: consts.GERUND,
    verbs: [
      ['admit', 'He admitted cheating on the test.'],
      ['advise', 'The doctor generally advised drinking low-fat milk.'],
      ['allow', 'Ireland doesn\'t allow smoking in bars.'],
      ['anticipate', 'I anticipated arriving late.'],
      ['appreciate', 'I appreciated her helping me.'],
      ['avoid', 'He avoided talking to her.'],
      ['begin', 'I began learning Chinese.'],
      ['can\'t bear', 'He can\'t bear having so much responsibility.'],
      ['can\'t help', 'He can\'t help talking so loudly.'],
      ['can\'t see', 'I can\'t see paying so much money for a car.'],
      ['can\'t stand', 'He can\'t stand her smoking in the office.'],
      ['cease', 'The government ceased providing free healthcare.'],
      ['complete', 'He completed renovating the house.'],
      ['consider', 'She considered moving to New York.'],
      ['continue', 'He continued talking.'],
      ['defend', 'The lawyer defended her making such statements.'],
      ['delay', 'He delayed doing his taxes.'],
      ['deny', 'He denied committing the crime.'],
      ['despise', 'She despises waking up early.'],
      ['discuss', 'We discussed working at the company.'],
      ['dislike', 'She dislikes working after 5 PM.'],
      ['don\'t mind', 'I don\'t mind helping you.'],
      ['dread', 'She dreads getting up at 5 AM.'],
      ['encourage', 'He encourages eating healthy foods.'],
      ['enjoy', 'We enjoy hiking.'],
      ['finish', 'He finished doing his homework.'],
      ['forget', 'I forgot giving you my book.'],
      ['hate', 'I hate cleaning the bathroom.'],
      ['imagine', 'He imagines working there one day.'],
      ['involve', 'The job involves traveling to Japan once a month.'],
      ['keep', 'She kept interrupting me.'],
      ['like', 'She likes listening to music.'],
      ['love', 'I love swimming.'],
      ['mention', 'He mentioned going to that college.'],
      ['mind', 'Do you mind waiting here for a few minutes.'],
      ['miss', 'She misses living near the beach.'],
      ['need', 'The aquarium needs cleaning.'],
      ['neglect', 'Sometimes she neglects doing her homework.'],
      ['permit', 'California does not permit smoking in restaurants.'],
      ['postpone', 'He postponed returning to Paris.'],
      ['practice', 'She practiced singing the song.'],
      ['prefer', 'He prefers sitting at the back of the movie theater.'],
      ['propose', 'I proposed having lunch at the beach.'],
      ['quit', 'She quit worrying about the problem.'],
      ['recall', 'Tom recalled using his credit card at the store.'],
      ['recollect', 'She recollected living in Kenya.'],
      ['recommend', 'Tony recommended taking the train.'],
      ['regret', 'She regretted saying that.'],
      ['remember', 'I remember telling her the address yesterday.'],
      ['report', 'He reported her stealing the money.'],
      ['require', 'The certificate requires completing two courses.'],
      ['resent', 'Nick resented Debbie\'s being there.'],
      ['resist', 'He resisted asking for help.'],
      ['risk', 'He risked being caught.'],
      ['start', 'He started studying harder.'],
      ['stop', 'She stopped working at 5 o\'clock.'],
      ['suggest', 'They suggested staying at the hotel.'],
      ['tolerate', 'I tolerated her talking.'],
      ['try', 'Sam tried opening the lock with a paperclip.'],
      ['understand', 'I understand his quitting.'],
      ['urge', 'They urge recycling bottles and paper.'],
    ],
  },
  {
    title: consts.INFINITIVE,
    verbs: [
      ['agree', 'Tom agreed to help me.'],
      ['appear', 'His health appeared to be better.'],
      ['arrange', 'Naomi arranged to stay with her cousin in Miami.'],
      ['ask', 'She asked to leave.'],
      ['begin', 'He began to talk.'],
      ['can\'t bear', 'He can\'t bear to be alone.'],
      ['can\'t stand', 'Nancy can\'t stand to work the late shift.'],
      ['care', 'He doesn\'t care to participate in the activity.'],
      ['cease', 'The government ceased to provide free healthcare.'],
      ['choose', 'I chose to help.'],
      ['claim', 'She claimed to be a princess.'],
      ['continue', 'She continued to talk.'],
      ['decide', 'We decided to go to Hawaii.'],
      ['demand', 'He demanded to speak to Mr. Harris.'],
      ['deserve', 'He deserves to go to jail.'],
      ['dread', 'I dread to think what might happen.'],
      ['expect', 'They expect to arrive early.'],
      ['fail', 'He failed to get enough money to pay for the new project.'],
      ['forget', 'I forgot to lock the door when I left.'],
      ['get (be allowed to)', 'Debbie gets to go to the concert next week! Why can\'t I?'],
      ['happen', 'She happened to be at the bank when it was robbed.'],
      ['hate', 'He hates to clean dishes.'],
      ['hesitate', 'She hesitated to tell me the problem.'],
      ['hope', 'I hope to begin college this year.'],
      ['intend', 'We intend to visit you next spring.'],
      ['learn', 'I learned to speak Japanese when I was a kid.'],
      ['like', 'Samantha likes to read.'],
      ['love', 'We love to scuba dive.'],
      ['manage', 'He managed to open the door without the key.'],
      ['need', 'I need to study.'],
      ['neglect', 'She neglected to tell me the date of the meeting.'],
      ['offer', 'Frank offered to drive us to the supermarket.'],
      ['plan', 'We plan to go to Europe this summer.'],
      ['prefer', 'He prefers to eat at 7 PM.'],
      ['prepare', 'They prepared to take the test.'],
      ['pretend', 'The child pretended to be a monster.'],
      ['promise', 'She promised to stop smoking.'],
      ['propose', 'Drew proposed to pay for the trip.'],
      ['refuse', 'The guard refused to let them enter the building.'],
      ['regret', 'I regret to inform you that your application was rejected.'],
      ['remember', 'Did you remember to lock the door when you left?'],
      ['seem', 'Nancy seemed to be disappointed.'],
      ['start', 'Marge started to talk really fast.'],
      ['swear', 'She swore to tell the truth.'],
      ['tend', 'He tends to be a little shy.'],
      ['threaten', 'He threatened to leave forever.'],
      ['try', 'Mary tried to lift the table, but it was too heavy.'],
      ['vow', 'He vowed to get revenge.'],
      ['wait', 'She waited to buy a movie ticket.'],
      ['want', 'I want to study Spanish.'],
      ['wish', 'I wish to stay.'],
      ['would like', 'We would like to start now. (meaning "wish" or "want")'],
      ['yearn', 'Melanie yearns to travel somewhere exotic.'],
    ],
  },
  {
    title: consts.VERB_REQUIRED_NOUN_INFINITIVE,
    verbs: [
      ['advise', 'I advised them to see a doctor.'],
      ['allow', 'Ireland doesn\'t allow people to smoke in bars.'],
      ['cause', 'He caused her to make a mistake.'],
      ['convince', 'Ned convinced me to quit my job.'],
      ['enable', 'Financial aid enabled the students to pay such expensive tuition fees.'],
      ['encourage', 'He encourages his patients to eat healthy foods.'],
      ['force', 'The commander forced the soldiers to march in the rain.'],
      ['get (cause to)', 'Isabelle got Mike to wash her car.'],
      ['hire', 'Mr. Donelly hired Sarah to work as a receptionist.'],
      ['invite', 'We invited them to join us.'],
      ['order', 'The police ordered him to put his hands in the air.'],
      ['permit', 'California doesn\'t permit people to fish without a fishing license.'],
      ['remind', 'They reminded me to pay the bills before the end of the month.'],
      ['require', 'The certificate requires students to complete two courses.'],
      ['tell', 'He told me to shut up.'],
      ['urge', 'They urge citizens to recycle bottles and paper.'],
      ['warn', 'She warned him not to be late.'],
    ],
  },
  {
    title: consts.VERB_OPTIONAL_NOUN_INFINITIVE,
    verbs: [
      ['ask', 'She asked him to leave.'],
      ['choose', 'I chose him to help out.'],
      ['expect', 'The expect him to arrive early.'],
      ['need', 'I need her to clean the house.'],
      ['prepare', 'They prepared her to take the test.'],
      ['promise', 'She promised him to stop smoking.'],
      ['threaten', 'He threatened her to leave forever.'],
      ['want', 'I want my son to study Spanish.'],
      ['wish', 'I wish him to stay.'],
      ['would like', 'We would like him to start now.'],
    ],
  },
  {
    title: consts.GERUND_OR_NOUN_INFINITIVE,
    verbs: [
      ['advise', 'I advised seeing a doctor.', 'I advised them to see a doctor.'],
      ['allow', 'Ireland doesn\'t allow smoking in bars.', 'Ireland doesn\'t allow people to smoke in bars.'],
      ['encourage', 'He encourages eating healthy foods.', 'He encourages his patients to eat healthy foods.'],
      ['permit', 'California doesn\'t permit fishing without a fishing license.', 'California doesn\'t permit people to fish without a fishing license.'],
      ['require', 'The certificate requires completing two courses.', 'The certificate requires students to complete two courses.'],
      ['urge', 'They urge recycling bottles and paper.', 'They urge citizens to recycle bottles and paper.'],
    ],
  },
  {
    title: consts.ADJECTIVE_PREPOSITION_COMBINATIONS_FOLLOWED_BY_GERUNDS,
    verbs: [
      ['accustomed to', 'He is accustomed to having his own office.'],
      ['addicted to', 'She is addicted to watching TV.'],
      ['afraid of', 'She is afraid of speaking in public.'],
      ['anxious about', 'Norma is anxious about making the presentation.'],
      ['bored of', 'I am bored of doing the same old job.'],
      ['capable of', 'He is capable of winning a gold medal.'],
      ['committed to', 'She is committed to improving her English.'],
      ['concerned about', 'Nancy was concerned about being late.'],
      ['content with', 'Tim is content with winning second place.'],
      ['dedicated to', 'The organization is dedicated to ending poverty.'],
      ['devoted to', 'The money will be devoted to protecting the environment.'],
      ['disappointed with', 'Fiona was disappointed with coming in third place.'],
      ['discouraged by', 'He was discouraged by not getting the job.'],
      ['excited about', 'The researcher was excited about going to Africa.'],
      ['famous for', 'That actor is famous for being extremely weird.'],
      ['fond of', 'She is fond of having picnics.'],
      ['frightened of', 'She is frightened of being alone at night.'],
      ['guilty of', 'The banker was guilty of stealing money.'],
      ['happy about', 'He was happy about winning the lottery.'],
      ['interested in', 'She is interested in becoming a doctor.'],
      ['involved in', 'He was involved in making the movie.'],
      ['known for', 'She was known for causing problems.'],
      ['opposed to', 'They are opposed to building a new road in the park.'],
      ['proud of', 'He was proud of having completed the marathon.'],
      ['remembered for', 'She is remembered for protecting mountain gorillas.'],
      ['responsible for', 'He is responsible for causing the damage.'],
      ['scared of', 'Tina is scared of being alone at night.'],
      ['terrified of', 'The surfer is terrified of being attacked by a shark.'],
      ['tired from', 'She is tired from working all day.'],
      ['tired of', 'Margaret is tired of making dinner every night.'],
      ['worried about', 'The hikers were worried about not having enough water.'],
    ],
  },
  {
    title: consts.NOUN_PREPOSITION_COMBINATIONS_FOLLOWED_BY_GERUNDS,
    verbs: [
      ['addiction to', 'His addiction to surfing the Internet is a problem.'],
      ['advantage of', 'He has the advantage of speaking English fluently.'],
      ['anxiety about', 'Her anxiety about speaking in public caused her to lose the job.'],
      ['belief in', 'His belief in not harming animals was something he learned from his mother.'],
      ['credit for', 'She took credit for improving the filing system.'],
      ['dedication to', 'His dedication to teaching was impressive.'],
      ['delay in', 'The delay in processing the visa caused problems.'],
      ['devotion to', 'His devotion to biking allowed him to win the competition.'],
      ['disadvantage of', 'The disadvantage of flying is that you can\'t see the scenery along the way.'],
      ['experience in', 'She has a great deal of experience in introducing new products to international markets.'],
      ['fear of', 'His fear of flying made travel difficult.'],
      ['fondness for', 'Her fondness for traveling led to her career in the travel industry.'],
      ['habit of', 'His habit of smoking in restaurants caused many problems in California.'],
      ['interest in', 'Her career as a pilot evolved out of her interest in flying.'],
      ['knowledge of', 'Her knowledge of climbing helped her during the competition.'],
      ['love of', 'His love of singing developed when he was a child.'],
      ['memory of', 'Their memories of traveling in Africa will stay with them forever.'],
      ['preference for', 'I think his preference for speaking his native language is natural.'],
      ['process of', 'The process of painting such a large mural is more complicated than you might think.'],
      ['reaction to', 'His reaction to winning the prize was quite funny.'],
      ['reason for', 'The main reason for taking the course is to improve your language skills.'],
      ['regret for', 'The criminal\'s regret for committing the crime did not convince the judge.'],
      ['report on', 'The magazine\'s report on choosing the right car was not well researched.'],
      ['reputation for', 'Her reputation for lying is well known.'],
      ['responsibility for', 'His responsibility for completing the project on time was acknowledged by the company.'],
      ['story about', 'I don\'t know if I believe his story about seeing a UFO.'],
      ['talent for', 'His talent for learning languages was impressive.'],
    ],
  },
  {
    title: consts.VERBS_FOLLOWED_BY_GERUNDS_OR_INFINITIVES_DIFFERENT_MEANING,
    verbs: [
      [
        'dread',
        {
          'Gerund': [
            ['She dreaded taking the test.', 'Usually "dread" is followed by a gerund.'],
          ],
          'Infinitive': [
            ['He dreaded to think of the consequences of his actions.', '"Dread" is sometimes used with infinitives such as "think" or "consider." In the sentence above, "dreaded to think" means "did not want to think."'],
          ],
        },
      ],
      [
        'forget',
        {
          'Gerund': [
            ['She forgot reading the book when she was a kid.', 'When "forget" is used with a gerund, it means "to forget that you have done something." The sentence above means that she read the book when she was a kid, and that she has forgotten that fact.'],
          ],
          'Infinitive': [
            ['She forgot to pay the rent this month.', 'When forget is used with an infinitive, it means "to forget that you need to do something." The sentence above means that she forgot that she needed to pay the rent.'],
          ],
        },
      ],
      [
        'keep',
        {
          'Gerund': [
            ['She kept talking.', '"Keep" is normally used with a gerund to mean that you continue doing an action.'],
          ],
          'Infinitive': [
            ['The attackers kept hostages to prevent the police from entering.', '"Keep" can also be used with an object followed by an infinitive, but then the infinitive takes on the meaning of "in order to... ." In the sentence above, the attackers kept hostages in order to prevent the police from entering.'],
          ],
        },
      ],
      [
        'need',
        {
          'Gerund': [
            ['The house needs cleaning.', 'When "need" is used with a gerund, it takes on a passive meaning. The sentence above means "the house needs to be cleaned."'],
          ],
          'Infinitive': [
            ['He needs to call his boss. OR He needs him to call his boss.', '"Need" is usually used with an infinitive or an object + an infinitive.'],
          ],
        },
      ],
      [
        'regret',
        {
          'Gerund': [
            ['I regretted being late to the interview.', '"Regret" is normally used with a gerund.'],
          ],
          'Infinitive': [
            ['We regret to inform you that your position at the company is being eliminated.', '"Regret" is sometimes used with infinitives such as "to inform." In the sentence above, "We regret to inform you" means "We wish we did not have to tell you (bad news)."'],
          ],
        },
      ],
      [
        'remember',
        {
          'Gerund': [
            ['I remember mentioning the meeting yesterday.', 'When "remember" is used with a gerund, it means "to remember that you have done something." The sentence above means that I mentioned the meeting, and that I remember the fact that I did that.'],
          ],
          'Infinitive': [
            ['He remembered to turn off the lights before he left.', 'When "remember" is used with an infinitive, it means "to remember that you need to do something." The sentence above means that he remembered that he needed to turn the lights off.'],
          ],
        },
      ],
      [
        'stop',
        {
          'Gerund': [
            ['He stopped smoking for health reasons.', '"Stop" is normally used with a gerund.'],
          ],
          'Infinitive': [
            ['He stopped to rest for a few minutes.', 'When "stop" is used with an infinitive, the infinitive takes on the meaning of "in order to."'],
          ],
        },
      ],
      [
        'try',
        {
          'Gerund': [
            ['She can\'t find a job. She tried looking in the paper, but there was nothing.', '"Try + gerund" means to try or to experiment with different methods to see if something works.'],
            ['She tried eating the snake soup, but she didn\'t like it.', '"Try + gerund" is often used when you experiment with something, but you do not really like it or want to do it again.'],
          ],
          'Infinitive': [
            ['She tried to climb the tree, but she couldn\'t even get off the ground.', 'When you "try to do" something, you want to do it, but you do not succeed in actually doing it.'],
            ['Try not to wake the baby when you get up tomorrow at 5 AM.', 'An infinitive is also used if you are asking someone to try something they may or may not be able to accomplish.'],
          ],
        },
      ],
    ],
  },
  {
    title: consts.VERBS_FOLLOWED_BY_GERUNDS_OR_INFINITIVES_SIMILAR_MEANING,
    verbs: [
      ['can\'t bear', 'He can\'t bear being alone.', 'He can\'t bear to be alone.'],
      ['can\'t stand', 'Nancy can\'t stand working the late shift.', 'Nancy can\'t stand to work the late shift.'],
      ['cease', 'The government ceased providing free health care.', 'The government ceased to provide free health care.'],
      ['continue', 'She continued talking.', 'She continued to talk.'],
      ['hate', 'He hates cleaning dishes.', 'He hates to clean dishes.'],
      ['like', 'Samantha likes reading.', 'Samantha likes to read.'],
      ['love', 'We love scuba diving.', 'We love to scuba dive.'],
      ['neglect', 'He neglected doing his daily chores.', 'He neglected to do his daily chores.'],
      ['prefer', 'He prefers eating at 7 PM.', 'He prefers to eat at 7 PM.'],
      ['propose', 'Drew proposed paying for the trip.', 'Drew proposed to pay for the trip.'],
    ],
  },
  {
    title: consts.GO_GERUND,
    verbs: [
      ['go boating'],
      ['go sailing'],
      ['go bowling'],
      ['go scuba diving'],
      ['go bungee jumping'],
      ['go shopping'],
      ['go camping'],
      ['go sightseeing'],
      ['go canoeing'],
      ['go skateboarding'],
      ['go climbing'],
      ['go skating'],
      ['go dancing'],
      ['go skiing'],
      ['go fishing'],
      ['go skinny-dipping'],
      ['go hiking'],
      ['go skydiving'],
      ['go horseback riding'],
      ['go sledding'],
      ['go hunting'],
      ['go snorkeling'],
      ['go jogging'],
      ['go snowboarding'],
      ['go kayaking'],
      ['go spearfishing'],
      ['go mountain climbing'],
      ['go surfing'],
      ['go paragliding'],
      ['go trekking'],
      ['go parasailing'],
      ['go water skiing'],
      ['go rollerblading'],
      ['go window shopping'],
      ['go running'],
      ['go windsurfing'],
    ],
  },
  {
    title: consts.BE_ADJECTIVE_COMBINATIONS_FOLLOWED_BY_INFINITIVES,
    verbs: [
      ['be amazed', 'He was amazed to discover the truth.'],
      ['be anxious', 'She was anxious to start her new job.'],
      ['be ashamed', 'He was ashamed to admit he had lied.'],
      ['be bound', 'She is bound to be elected class president.'],
      ['be careful', 'They were careful not to reveal the winner of the prize until the end.'],
      ['be certain', 'She is certain to get the job.'],
      ['be content', 'The student was content to receive second place in the competition.'],
      ['be delighted', 'We were delighted to be invited to the wedding.'],
      ['be determined', 'He was determined to finish the marathon.'],
      ['be eager', 'He was eager to begin.'],
      ['be eligible', 'They were not eligible to participate in the program.'],
      ['be fortunate', 'She was fortunate to receive the research grant.'],
      ['be glad', 'I would be glad to help out.'],
      ['be happy', 'She was happy to see them at the party.'],
      ['be hesitant', 'Mary was hesitant to say anything.'],
      ['be liable', 'The mountain climber is liable to hurt himself if he doesn\'t use well-made equipment.'],
      ['be likely', 'They are likely to show up at any time.'],
      ['be lucky', 'You were lucky to have such an opportunity.'],
      ['be pleased', 'I am pleased to meet you.'],
      ['be proud', 'He was proud to have been chosen to lead the project.'],
      ['be ready', 'I\'m ready to go now.'],
      ['be reluctant', 'The witness was reluctant to reveal what he had seen.'],
      ['be sad', 'She was really sad to leave.'],
      ['be shocked', 'He was shocked to discover the truth.'],
      ['be sorry', 'I am sorry to have to tell you that the tickets are sold out.'],
      ['be surprised', 'She was surprised to discover that he had never learned how to swim.'],
    ],
  },
  {
    title: consts.NOUNS_FOLLOWED_BY_INFINITIVES,
    verbs: [
      ['advice', 'His advice to continue was good.'],
      ['appeal', 'The appeal to reduce pollution was ineffective.'],
      ['attempt', 'Her attempt to locate them was unsuccessful.'],
      ['chance', 'In Britain, you will have a chance to improve your English.'],
      ['decision', 'The decision to increase taxes was not popular.'],
      ['desire', 'His desire to get a good job motivated him.'],
      ['dream', 'Her dream to become an actress was never realized.'],
      ['goal', 'His goal to run a marathon seemed unrealistic.'],
      ['motivation', 'Her motivation to enter university impressed them.'],
      ['need', 'Bob\'s need to be the center of attention was irritating.'],
      ['opportunity', 'The opportunity to live in New York interested Sandra.'],
      ['order', 'They followed the general\'s order to retreat.'],
      ['permission', 'Permission to enter the area was difficult to get.'],
      ['plan', 'Sandy\'s plan to move to Madrid bothered her parents.'],
      ['preparation', 'NASA\'s preparations to launch on Monday moved forward.'],
      ['proposal', 'Her proposal to host the party impressed the committee.'],
      ['recommendation', 'His recommendation to close the school upset the community.'],
      ['refusal', 'Debra\'s refusal to help did not go unnoticed.'],
      ['reminder', 'Her reminder to review the vocabulary helped me pass the test.'],
      ['request', 'Their request to participate was granted.'],
      ['requirement', 'Their requirement to speak four languages was unreasonable.'],
      ['suggestion', 'His suggestion to leave seemed like a good idea.'],
      ['tendency', 'His tendency to tap his desk during a test annoyed me.'],
      ['wish', 'Her wish to be treated normally was respected.'],
      ['way', 'One way to improve your English is to read novels.'],

    ],
  },
  {
    title: consts.EXPRESSIONS_FOLLOWED_BY_VERB_ING,
    verbs: [
      ['have (some) problems', 'He had some problems reading without his glasses.'],
      ['have a difficult time', 'She had a difficult time hiking up the mountain.'],
      ['have a good time', 'They had a good time snorkeling.'],
      ['have a hard time', 'She had a hard time explaining the situation.'],
      ['have a problem', 'Debbie had a problem understanding his accent.'],
      ['have an easy time', 'She had an easy time selling the delicious cookies.'],
      ['have difficulty', 'Wanda had difficulty translating the letter by herself.'],
      ['have fun', 'The had fun skiing.'],
      ['have no difficulty', 'They had no difficulty finding a discount flight to London.'],
      ['have no problem', 'Francis had no problem getting from the airport to the hotel.'],
      ['spend one\'s time', 'He always spends his time working out at the gym.'],
      ['waste one\'s time', 'She always wastes her time playing video games.'],
    ],
  },
  {
    title: consts.LOCATION_VERBS_FOLLOWED_BY_VERB_ING,
    verbs: [
      ['cling', 'She clung to the bottom of the bridge trying to resist the swift current.'],
      ['cower', 'The family cowered in their basement hoping the tornado would change directions.'],
      ['crouch', 'The mountain lion crouched on a bolder watching the deer walk by below.'],
      ['hang', 'The monkey hung in the tree chewing on the ripened fruit.'],
      ['lean', 'Tom leaned against the wall resting a few moments before he continued on.'],
      ['lie', 'He lay in bed thinking about the day\'s events.'],
      ['sit', 'She always sits on the couch watching TV.'],
      ['stand', 'Nancy stood at the corner looking up and down the street.'],
    ],
  },
];
